### ISSUE TITLE
Grain Distributions should be pushed straight to master

### ISSUE THREAD

**Issue by topocount** [sourcecred/cred#149]
Currently Grain Distributions automatically generate a new Pull Request. This is a bit cumbersome for higher trust communities, so we want to push grain distributions straight to master in the sourcecred/cred repo at least.

@hammadj and @befitsandpiper would you want this change for your instances as well?

**Comment by befitsandpiper** [comment]
I doubt this makes sense for 1hive given that a lot of manual adding new folks, changing weights, and updating is done every week, so this would probably be more of a headache than helpful. If opting in and other parts of the administration process were automated it might not be as big of a deal.

Also, I'm pretty convinced the 1hive live site is totally botched and wouldn't trust it to have accurate enough scores for handling distributions.

**Comment by decentralion** [comment]
@befitsandpiper why is the live site totally botched? maybe file an issue on that somewhere?

**Comment by topocount** [comment]
we need to navigate some github permissions together to get this working as intended.
