### ISSUE TITLE
Possibly a mistake in last grain sales?

### ISSUE THREAD

**Issue by Beanow** [sourcecred/cred#329]
I believe there may be a mixup. Unless I'm missing some major fee or a decision to no longer redeem 1:1.
For the requested 4000 grain
![image](https://user-images.githubusercontent.com/497556/128845081-c952c82b-17a6-4222-9005-596051b4cc66.png)

I received 3000 USDC.
![image](https://user-images.githubusercontent.com/497556/128845119-c2906f7f-b11e-4205-a16f-6f26948310ad.png)

_Originally posted by @Beanow in https://github.com/sourcecred/cred/issues/328#issuecomment-895885647_

Elevating to an issue so it doesn't get hidden in an already merged PR.

**Comment by blueridger** [comment]
We have unpegged grain redemption from 1:1 to a ratio that matches remaining funding. Details can be seen in this meeting note: https://roamresearch.com/#/app/SourceCred/page/8TLq9y-Xq

Sorry for the confusion.

**Comment by blueridger** [comment]
Updated the Grain Sale Request form to reflect the unpegging and the monthly cap.
